# Python Packages For Applied Mathematics and PyGOM Tutorial

By Martin Grunnill
Given on 16<sup>th</sup> January as part of York University's Practicum in Industrial and Applied Math.

Python is one of the most commonly used coding languages, hosting an extensive array of packages in Data Science, Mathematics and Machine Learning. With a syntax that emphasis readability, Python is considered one of the easiest coding languages to learn. It is also free and open source. Therefore, Python code produced in a research project can be more easily shared with others and is more accessible outside of academic institutions.

This Jupyter notebook is divided into three sections:
1. Numpy: provides support for handling multidimensional arrays and matrices.
2. Pandas: provides access to Dataframe and Serries objects. Dataframes being similar to spreadsheets, with Series being a one-dimensional variant.
3. PyGOM: a toolbox for modeling with Ordinary Differential Equations (ODEs). Having been developed by the UK Health Security Agency, PyGOM has an emphasis on epidemiological modelling. Providing functionality not only for solving ODEs, parameter estimation and stochastic simulation, but methods for deriving the basic reproduction number R0.

# 1. Numpy

At the core of numpy is the ndarray object. Although having similarities to lists (and tupples) in terms of indexing, Ndarrays have some key differences:
* They are of a fixed sized from creation (similar to a tupple). Changing the deminsions of a ndarray results in the creation of a new ndarray.
* They facilitate mathmatical operations at a much faster speed and with less code.

This final point has led to numpy array's being the basis of many python packages in mathematical and scientific computing. As such python based work in this area requires often requires knowledge of numpy arrays.

# 1.1 Creating Arrays.

Lets import numpy and create some ndarrays.

In [1]:
import numpy as np # numpy is often shotened to np in coding:

array_1d = np.array([2,-1,6, 11, 3.14])

In [2]:
array_1d = np.array([3,-1, 11, 3.14])
array_2d = np.array([[ 3, -1 ],
                     [11, 3.14]])
array_3d = np.array([[[ 3, -1 ,2], [2,3.14,3]], [[11, 3.14, 8], [10,11,12]]])

display(array_1d,array_2d,array_3d)

array([ 3.  , -1.  , 11.  ,  3.14])

array([[ 3.  , -1.  ],
       [11.  ,  3.14]])

array([[[ 3.  , -1.  ,  2.  ],
        [ 2.  ,  3.14,  3.  ]],

       [[11.  ,  3.14,  8.  ],
        [10.  , 11.  , 12.  ]]])

Arrays of sequences can be generated using `arange` in similar manner to `range`. **Note** this has an advantage over `range` in that it can handle floats.

In [3]:
display(np.arange(2,5), np.arange(2,3,0.25))

array([2, 3, 4])

array([2.  , 2.25, 2.5 , 2.75])

There are several methods for creating arrays of repeated values:

In [4]:
ones = np.ones((3, 4))
zeros = np.zeros([1,2])
trues = np.full((2,3),True)
display(ones,zeros,trues)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[0., 0.]])

array([[ True,  True,  True],
       [ True,  True,  True]])

# 1.1 Array shape and indexing.

An arrays deminsions can be determined using `.shape`:

In [5]:
display(array_1d.shape,array_2d.shape,array_3d.shape)

(4,)

(2, 2)

(2, 2, 3)

When indexing deminsions are indexed in the same order they are created. This means rows first then columns:

In [6]:
display(array_1d[3], array_2d[1,0], array_3d[1, 1,0])

3.14

11.0

10.0

As well as slices `:` multiple single elements can be indexed:

In [7]:
display(array_1d[:3], array_2d[[1,0],[0,1]])

array([ 3., -1., 11.])

array([11., -1.])

## 1.3 Element wise operations.

Elementwise operations are accessed via the same methods as carried out on floats and ints:

In [8]:
array_2d_b = np.array([[ 8, -5 ],
                       [10, 6]])
addition_array = array_2d + array_2d_b
sub_array = addition_array - array_2d_b
mul_array = array_2d * array_2d_b
div_array = mul_array/ array_2d_b
display(addition_array, sub_array, mul_array, div_array)

array([[11.  , -6.  ],
       [21.  ,  9.14]])

array([[ 3.  , -1.  ],
       [11.  ,  3.14]])

array([[ 24.  ,   5.  ],
       [110.  ,  18.84]])

array([[ 3.  , -1.  ],
       [11.  ,  3.14]])

## 1.4 Further tutorials and reading on numpy.

Now that these basics are covered you may wish to look up Numpy's:
1. [user guide](https://numpy.org/doc/stable/user/index.html#user)
2. [Linear algebra features](https://numpy.org/doc/stable/reference/routines.linalg.html)
3. [Random number generators](https://numpy.org/doc/stable/reference/random/generator.html)

# 2. PyGOM

PyGOM — A Python Package for Simplifying Modelling with Systems of Ordinary Differential Equations https://arxiv.org/pdf/1803.06934.pdf



# 2.1 Setting up an ODE system

Using PyGOM, we will set up a simple SIR model. This model has many simplifying assumptions, including:
- no births or deaths
- homogeneous mixing
- no interventions

Suscebtible population (S) are those that can catch the disease. A susceptible person becomes infected when they interact with an infected person. The chance of this interaction resulting in infection is described with parameter $\beta$.

$ \frac{dS}{dt} = -\beta S \frac{I}{N}$

Infected population (I) recover at rate $\gamma$.

$ \frac{dI}{dt} = \beta S \frac{I}{N} - \gamma I$

Removed population (R) are those who have immunity (described with initial conditions) or have recovered/died from the disease.

$ \frac{dR}{dt} = \gamma I$

Total population (N) is given by $N = S + I + R$.

In [9]:
from pygom import Transition, TransitionType, SimulateOde # import necesary objects from pygom

states = ['S', 'I', 'R']  # Set the states
params = ['beta', 'gamma', 'N'] # Set the parameters.
transitions = [Transition(origin='S', destination='I', equation='beta*S*I/N',
                          transition_type=TransitionType.T),
               Transition(origin='I', destination='R', equation='gamma*I',
                          transition_type=TransitionType.T)]
model = SimulateOde(states, params, transition=transitions)